# This notebook is to score the pre-test survey responses collected for the LeagueComms Project

In [1]:
# import data
import numpy as np
import pandas as pd

raw_survey_scores_df = pd.read_csv(r'D:\Projects\UG-league-project\all-survey-data.csv')

# PRE-TEST
# reverse score R keys in HEXA
# calculate average for each player
# calculate average, min, max and variance for each team

# sum the score for each player for Reading Mind in Eyes Test (RMET)
# calculate average for each player
# calculate average, min, max and variance for each team

In [2]:
raw_survey_scores_df.head()

,team_no,age,rank,gender,role,match_id,outcome,AGR3,EX4,EMO5,...,TASK3,SOC1,TI1,TI2,TI3,TI4,How likely are you to return to this team if the team were asked to play again tomorrow?,Is there any teammate(s) that you would be happy to play with again? You can make multiple selections.,Please provide more details for your answer to the previous question (about teammates you would play with in the future). Why would you be happy to play with them again? Try to be specific.,Please leave any additional comments or feedback here.
0,1,25,Platinum I,Male,Mid,5056494058,0,4.0,4.0,2.0,...,6,6,7,6,7,6,5,"Top,Support",they were nice people and got along with them ...,NaN
1,1,22,Platinum I,Male,Top,5056494058,0,2.0,3.0,2.0,...,6,4,4,6,6,5,6,"Mid,Support","Seemed like good people, no flame towards each...","Really sad we couldn't play as 5, maybe try to..."
2,1,20,Platinum II,Male,Support,5056494058,0,4.0,5.0,2.0,...,7,6,7,6,7,7,7,"Mid,Top",they were pretty chill during the game even th...,"was really fun, glad to be a part of it. Would..."
3,2,21,Platinum IV,Female,Mid,5064844365,1,4.0,4.0,2.0,...,6,5,6,7,6,6,6,"Top,Jungle",We shared a decent amount of good communicatio...,Even though I'm mostly satisfied over my exper...
4,2,22,Platinum II,Male,Bot,5064844365,1,4.0,4.0,4.0,...,6,6,7,7,7,6,7,"Mid,Top,Jungle,Support",We had very little time and all I could gather...,I kind of got carried a bit and just served as...

# Reverse score the HEXA keys

In [3]:
# to reverse score the keys, separate the positive from the negatively keyed

HEXA_positive = ['AGR3', 'EX4', 'EMO5', 'HH6', 'EMO11', 'EX16', 'EMO17', 'HH18', 'EX22', 'EMO23', 'AGR27', 'EMO29', 'AGR33', 'EX34', 'HH36', 'AGR39', 'EX40', 'AGR45', 'EMO47', 'AGR51', 'HH54', 'EX58']

HEXA_negative = ['AGR9R', 'EX10R', 'HH12R', 'AGR15R', 'AGR21R', 'HH24R', 'EX28R', 'HH30R', 'EMO35R', 'EMO41R', 'HH42R', 'EX46R', 'HH48R', 'EX52R', 'EMO53R', 'AGR57R', 'EMO59R', 'HH60R']

len(HEXA_positive)

22

In [4]:
len(HEXA_negative)

18

## Function to reverse score HEXA factors

In [5]:
# create a function to reverse score the items
# df = data frame, high = highest score, col = list of columns to reverse score 
def reverse_scoring_hexa(df, high, cols):
    df[cols] = high - df[cols]
                    
    return df

recoded_survey_scores_df = reverse_scoring_hexa(raw_survey_scores_df, 6, HEXA_negative)

recoded_survey_scores_df.to_csv('recoded_survey_scores.csv')

# Function to calculate factors

https://hexaco.org/downloads/ScoringKeys_60.pdf

In [6]:
# For factor scores: calculate means across all items in the factor

# creating a new column that represents the mean, for each factor
recoded_survey_scores_df['HH_mean'] = recoded_survey_scores_df[['HH6', 'HH12R', 'HH18', 'HH24R', 'HH30R', 'HH36', 'HH42R', 'HH48R', 'HH54', 'HH60R']].mean(axis=1)
recoded_survey_scores_df['EMO_mean'] = recoded_survey_scores_df[['EMO5', 'EMO11', 'EMO17', 'EMO23', 'EMO29', 'EMO35R', 'EMO41R', 'EMO47', 'EMO59R','EMO53R']].mean(axis=1)
recoded_survey_scores_df['EX_mean'] = recoded_survey_scores_df[['EX4', 'EX10R', 'EX16', 'EX22', 'EX28R', 'EX34', 'EX40', 'EX46R', 'EX52R', 'EX58']].mean(axis=1)
recoded_survey_scores_df['AGR_mean'] = recoded_survey_scores_df[['AGR3', 'AGR9R', 'AGR15R', 'AGR21R', 'AGR27', 'AGR33', 'AGR39', 'AGR45', 'AGR51', 'AGR57R']].mean(axis=1)
recoded_survey_scores_df['RME_total_score'] = recoded_survey_scores_df[['RME1', 'RME2', 'RME3', 'RME4', 'RME5', 'RME6', 'RME7', 'RME8', 'RME9', 'RME10', 'RME11', 'RME12', 
                                                                       'RME13', 'RME14', 'RME15', 'RME16', 'RME17', 'RME18', 'RME19', 'RME20', 'RME21',
                                                                       'RME22', 'RME23', 'RME24', 'RME25', 'RME26', 'RME27', 'RME28', 'RME29', 'RME30', 'RME31', 'RME32',
                                                                       'RME33', 'RME34', 'RME35', 'RME36']].sum(axis=1)


recoded_survey_scores_df.to_csv('with_hexa_means.csv')

recoded_survey_scores_df.head()

# For facet scores: calculate means across all items in the facet. The 60 item test is not expected to have high internal validity for facet-level scores (ignoring this)

,team_no,age,rank,gender,role,match_id,outcome,AGR3,EX4,EMO5,...,TI4,How likely are you to return to this team if the team were asked to play again tomorrow?,Is there any teammate(s) that you would be happy to play with again? You can make multiple selections.,Please provide more details for your answer to the previous question (about teammates you would play with in the future). Why would you be happy to play with them again? Try to be specific.,Please leave any additional comments or feedback here.,HH_mean,EMO_mean,EX_mean,AGR_mean,RME_total_score
0,1,25,Platinum I,Male,Mid,5056494058,0,4.0,4.0,2.0,...,6,5,"Top,Support",they were nice people and got along with them ...,NaN,4.3,2.5,3.7,3.7,26.0
1,1,22,Platinum I,Male,Top,5056494058,0,2.0,3.0,2.0,...,5,6,"Mid,Support","Seemed like good people, no flame towards each...","Really sad we couldn't play as 5, maybe try to...",3.0,3.1,2.4,3.0,31.0
2,1,20,Platinum II,Male,Support,5056494058,0,4.0,5.0,2.0,...,7,7,"Mid,Top",they were pretty chill during the game even th...,"was really fun, glad to be a part of it. Would...",3.3,2.0,4.1,4.2,21.0
3,2,21,Platinum IV,Female,Mid,5064844365,1,4.0,4.0,2.0,...,6,6,"Top,Jungle",We shared a decent amount of good communicatio...,Even though I'm mostly satisfied over my exper...,3.4,2.9,2.6,3.6,29.0
4,2,22,Platinum II,Male,Bot,5064844365,1,4.0,4.0,4.0,...,6,7,"Mid,Top,Jungle,Support",We had very little time and all I could gather...,I kind of got carried a bit and just served as...,3.2,3.0,2.6,3.1,24.0

# Get summary stats of each team using the describe() function

In [7]:
# calculate summary stats for each personality factor per team
HH_summary_stats_df = recoded_survey_scores_df.groupby('team_no')['HH_mean'].describe()
EMO_summary_stats_df = recoded_survey_scores_df.groupby('team_no')['EMO_mean'].describe()
EX_summary_stats_df = recoded_survey_scores_df.groupby('team_no')['EX_mean'].describe()
AGR_summary_stats_df = recoded_survey_scores_df.groupby('team_no')['AGR_mean'].describe()
RME_summary_stats_df = recoded_survey_scores_df.groupby('team_no')['RME_total_score'].describe()

In [8]:
HH_summary_stats_df

         count      mean       std  min    25%   50%    75%  max
team_no
1          3.0  3.533333  0.680686  3.0  3.150  3.30  3.800  4.3
2          5.0  3.320000  0.083666  3.2  3.300  3.30  3.400  3.4
3          3.0  3.633333  0.404145  3.4  3.400  3.40  3.750  4.1
4          5.0  2.960000  0.502991  2.2  2.900  3.00  3.100  3.6
5          5.0  2.820000  0.605805  2.1  2.500  2.60  3.400  3.5
6          5.0  3.540000  0.507937  2.8  3.300  3.60  4.000  4.0
7          3.0  3.300000  0.360555  2.9  3.150  3.40  3.500  3.6
8          5.0  3.440000  0.577062  2.8  3.100  3.20  4.000  4.1
9          3.0  3.866667  0.152753  3.7  3.800  3.90  3.950  4.0
10         3.0  3.300000  1.135782  2.0  2.900  3.80  3.950  4.1
11         5.0  3.500000  0.418330  3.0  3.300  3.40  3.700  4.1
12         3.0  3.466667  0.416333  3.0  3.300  3.60  3.700  3.8
13         5.0  3.320000  0.449444  2.9  3.000  3.10  3.700  3.9
14         5.0  3.320000  0.704982  2.6  2.700  3.20  4.000  4.1
15         5.0  3.440000  0.230217  3.2  3.300  3.40  3.500  3.8
16         2.0  3.800000  1.131371  3.0  3.400  3.80  4.200  4.6
17         4.0  3.025000  1.405643  1.8  1.950  2.75  3.825  4.8
18         3.0  3.333333  1.050397  2.3  2.800  3.30  3.850  4.4
19         2.0  2.900000  0.707107  2.4  2.650  2.90  3.150  3.4
20         3.0  2.966667  0.550757  2.6  2.650  2.70  3.150  3.6
21         3.0  3.700000  0.360555  3.4  3.500  3.60  3.850  4.1
22         5.0  3.480000  0.614003  2.6  3.300  3.40  3.900  4.2
23         3.0  3.666667  0.850490  2.8  3.250  3.70  4.100  4.5
24         3.0  3.366667  0.493288  2.8  3.200  3.60  3.650  3.7
25         3.0  4.466667  0.305505  4.2  4.300  4.40  4.600  4.8
26         3.0  3.500000  0.173205  3.4  3.400  3.40  3.550  3.7
27         3.0  3.033333  0.838650  2.5  2.550  2.60  3.300  4.0
28         5.0  3.360000  0.614817  2.7  2.900  3.20  3.900  4.1
29         3.0  3.266667  0.251661  3.0  3.150  3.30  3.400  3.5
30         2.0  4.050000  0.070711  4.0  4.025  4.05  4.075  4.1
31         5.0  3.360000  0.820366  2.4  2.900  3.10  4.000  4.4
32         5.0  3.860000  0.577062  2.9  3.800  4.00  4.300  4.3
33         3.0  3.900000  0.500000  3.4  3.650  3.90  4.150  4.4
34         5.0  3.140000  0.304959  2.9  2.900  3.00  3.300  3.6
35         3.0  3.233333  0.115470  3.1  3.200  3.30  3.300  3.3
36         5.0  3.280000  0.898332  1.8  3.300  3.40  3.700  4.2
37         3.0  3.700000  0.624500  3.0  3.450  3.90  4.050  4.2
38         3.0  3.666667  0.321455  3.3  3.550  3.80  3.850  3.9
39         3.0  3.433333  0.152753  3.3  3.350  3.40  3.500  3.6
40         3.0  3.100000  0.793725  2.2  2.800  3.40  3.550  3.7
41         3.0  3.866667  0.416333  3.4  3.700  4.00  4.100  4.2
42         5.0  3.120000  0.804363  2.1  2.600  3.30  3.400  4.2
43         3.0  3.700000  0.264575  3.4  3.600  3.80  3.850  3.9
44         3.0  3.500000  0.346410  3.3  3.300  3.30  3.600  3.9
45         3.0  3.566667  0.461880  3.3  3.300  3.30  3.700  4.1
46         3.0  4.166667  0.152753  4.0  4.100  4.20  4.250  4.3
47         3.0  3.566667  1.289703  2.5  2.850  3.20  4.100  5.0
48         2.0  3.850000  0.777817  3.3  3.575  3.85  4.125  4.4
49         2.0  3.650000  0.494975  3.3  3.475  3.65  3.825  4.0

## Rename the column names to identify columns after merging df

In [9]:
# rename the columns 
HH_summary_stats_df = HH_summary_stats_df.rename(columns={"mean": "HH_mean", "std": "HH_std", "min": "HH_min", "25%" : "HH_25_percent", "50%" : "HH_50_percent", "75%" : "HH_75_percent", "max" : "HH_max"})
EMO_summary_stats_df = EMO_summary_stats_df.rename(columns={"mean": "EMO_mean", "std": "EMO_std", "min": "EMO_min", "25%" : "EMO_25_percent", "50%" : "EMO_50_percent", "75%" : "EMO_75_percent", "max" : "EMO_max"})
EX_summary_stats_df = EX_summary_stats_df.rename(columns={"mean": "EX_mean", "std": "EX_std", "min": "EX_min", "25%" : "EX_25_percent", "50%" : "EX_50_percent", "75%" : "EX_75_percent", "max" : "EX_max"})
AGR_summary_stats_df = AGR_summary_stats_df.rename(columns={"mean": "AGR_mean", "std": "AGR_std", "min": "AGR_min", "25%" : "AGR_25_percent", "50%" : "AGR_50_percent", "75%" : "AGR_75_percent", "max" : "AGR_max"})
RME_summary_stats_df = RME_summary_stats_df.rename(columns={"mean": "RME_mean", "std": "RME_std", "min": "RME_min", "25%" : "RME_25_percent", "50%" : "RME_50_percent", "75%" : "RME_75_percent", "max" : "RME_max"})

In [10]:
frames = [HH_summary_stats_df, EMO_summary_stats_df, EX_summary_stats_df, AGR_summary_stats_df, RME_summary_stats_df]
pre_test_summary_stats = pd.concat(frames, axis=1)

In [11]:
# Adding the match_id and match_outcome

match_info_df = recoded_survey_scores_df.loc[:, ['team_no', 'match_id', 'outcome']]

# drop duplicates so you only have one entry per team
match_info_df = match_info_df.drop_duplicates()

## Join match info and survey scores together
## Save it out as a csv

In [13]:
summary_stats = (pd.merge(match_info_df, pre_test_summary_stats, on='team_no'))

# save to csv
# remove index column of df
summary_stats.to_csv('pre_test_summary_stats.csv', index = False)